# Generated by Django 5.0.4 on 2024-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
    ]
