# Generated by Django 5.0.4 on 2024-04-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('Address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='doctor',
            name='designation',
            field=models.CharField(max_length=20),
        ),
    ]
