# Generated by Django 5.0.4 on 2024-04-29 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0003_topic_doctor_user_alter_doctor_designation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individual',
            old_name='Address',
            new_name='address',
        ),
        migrations.AddField(
            model_name='individual',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='individual',
            name='designation',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='individual',
            name='gender',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
