# Generated by Django 5.0.4 on 2024-04-29 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehrapp', '0004_rename_address_individual_address_individual_dob_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individual',
            name='designation',
        ),
        migrations.AlterField(
            model_name='individual',
            name='DOB',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='individual',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
